sudo: false
language: python

python:
  - '2.7'

install:
  - pip install .
  - pip install coveralls
  - pip install codacy-coverage

script:
  - python setup.py coverage
  - coverage xml

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml

deploy:
  provider: pypi
  user: kronenthaler
  password:
    secure: wJTcHIa1sbXxE4FnLux/fUI+OqZl8tM3EuvPckC7FaYKFzVbFG63xHhpThZxOVF5295nxHBFIBPSm/wA+6wOjvDazaPd3Kvw+BlQqPOaUPuJEfeK9R0IfRB0ojkn7nXmhhiUJiO3UzNrCFsMdt9zMCzu7jih/r7DCv8pYb66CuQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kronenthaler/mod-pbxproj

env:
  secure: "gkO3U+6A5Nspsz/lWcpKzeTkLRvER2B+L7fLhAULYlhJ7/ZvHw2rTdWSZkDfY38VojS/Q/bdEk4OHcBga2Lm0v71iD0pGsB0bH8WwDL5eDeL5dvwE3k8OoFIzk5WY1IDPBk8JH9Hr6nz+oQwtK9aQTOItZcz+NAJ+wY58XJSGu0="
